app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
  packages: all
  extensions:
    - page:catalog:
        config:
          path: /
    - page:tech-radar:
        config:
          path: /tech-radar

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    host: 0.0.0.0
  reading:
    allow:
      - host: raw.githubusercontent.com
      - host: github.com
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: 127.0.0.1
      port: 9470
      user: postgres
      password: postgres123
      database: backstage

integrations:
  github:
    - host: github.com
      token: ${GIT_TOKEN}

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
    okta:
      development:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_AUDIENCE}
      production:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_AUDIENCE}

scaffolder:
  defaultAuthor:
    name: Backstage
    email: backstage@elitecorpusa.com

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group, User, Template]
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
    - type: url
      target: https://github.com/udhayakiran-stack/template-structure/blob/main/template.yaml
      rules:
        - allow: [Template]

permission:
  enabled: true

mcpActions:
  name: My Company Backstage
  description: Tools for managing your software catalog and templates