app:
  baseUrl: ${APP_BASE_URL}

organization:
  name: My Company

backend:
  baseUrl: ${APP_BASE_URL}

  auth:
    # keys:
    #   - secret: ${BACKEND_SECRET}

  listen:
    port: ${PORT}

  cors:
    origin: ${APP_BASE_URL}
    methods:
      - GET
      - HEAD
      - PATCH
      - POST
      - PUT
      - DELETE
    credentials: true

  reading:
    allow:
      - host: raw.githubusercontent.com
      - host: github.com

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

auth:
  environment: production

  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        
    okta:
      production:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_AUDIENCE}

techdocs:
  builder: external

  generator:
    runIn: local

  publisher:
    type: googleGcs
    googleGcs:
      bucketName: ${PROJECT_ID}-techdocs

scaffolder:
  defaultAuthor:
    name: Backstage
    email: backstage@elitecorpusa.com

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration

  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
        - Group
        - User
        - Template

  locations:
    - type: url
      target: https://github.com/udhayakiran-stack/template-structure/blob/main/template.yaml
      rules:
        - allow:
            - Template

permission:
  enabled: true

mcpActions:
  name: My Company Backstage
  description: Tools for managing your software catalog and developer portal